networks:
  proxy-network:
    external: true

services:
  politzek-frontend:
    container_name: politzek-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000
    env_file: ".env"
    networks:
      - proxy-network