fragment PrisonerItem on airtable_data_edge {
  id
  created_time
  case_categories
  name
  description
  formatted_description
  articles
  photo
  coordinates
  institution_short_name
  address
  date_of_arrest
  address_for_letters
  date_of_birth
  age
  gender
  region
  status
  published
  interests
  can_write
  slug
  last_sync
  release_date
  rosfin
  rosfin_start
  rosfin_end
  sentence
}

query prisoners($offset: Int, $filter: airtable_data_edgeFilter) {
  airtable_data_edgeCollection(first: $offset, filter: $filter) {
    edges {
      node {
        ...PrisonerItem
      }
    }
  }
}
